version: "3.7"

services:
 
  urbot:
    restart: always
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    image: urbot
    build:
      args:
        - SSH_KEY=${SSH_KEY}
      context: .
      dockerfile: Dockerfile
    env_file:
      - env.production.secret
    networks:
      - net
    command:
      [
        "yarn",
        "start:development:production",
      ]
    stdin_open: true
    tty: true


networks:
  net:
